# Config file used by .github/workflows/labeler.yml

# This file matches file/folder changes to labels. See https://github.com/actions/labeler for more information.

# e.g to add the test label to any changes in the /tests directory:

# test:
#   - tests/*

ghActions:
- changed-files:
  - any-glob-to-any-file: [.github/*]
documentation:
- changed-files:
  - any-glob-to-any-file: ['**/*.md']
jenkins:
- changed-files:
  - any-glob-to-any-file: [build-farm/*]
aix:
- changed-files:
  - any-glob-to-any-file: [build-farm/platform-specific-configurations/aix.sh]
alpine-linux:
- changed-files:
  - any-glob-to-any-file: [build-farm/platform-specific-configurations/alpine-linux.sh]
macos:
- changed-files:
  - any-glob-to-any-file: [build-farm/platform-specific-configurations/mac.sh]
solaris:
- changed-files:
  - any-glob-to-any-file: [build-farm/platform-specific-configurations/solaris.sh]
windows:
- changed-files:
  - any-glob-to-any-file: [build-farm/platform-specific-configurations/windows.sh]
docker:
- changed-files:
  - any-glob-to-any-file: [docker/*, docker-build.sh]
testing:
- changed-files:
  - any-glob-to-any-file: [tests/*]
security:
- changed-files:
  - any-glob-to-any-file: [security/*, SECURITY.md, sbin/sig_check/*]
installer:
- changed-files:
  - any-glob-to-any-file: [build-farm/sign-releases.sh, sign.sh]
