---
# Runs a script to triage the latest timer-initiated Temurin build pipelines.

name: "Build Autotriage"

on:
  schedule:
    - cron: '0 0 * * MON'

env:
  TRIAGE_SCRIPT: "tooling/build_autotriage/build_autotriage.sh"

jobs:
  autotriage:
    permissions:
      contents: read
      issues: write 
    runs-on: ubuntu-latest
    name: Run Build Triage
    if: github.repository == 'adoptium/temurin-build'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: "Run Build Auto Triage"
        run: bash "${PWD}/${TRIAGE_SCRIPT}" jdk8u jdk11u jdk17u jdk21u jdk22 jdk23head

      - name: Create Issue From File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        with:
          filename: ./build_triage_output.md
