---
name: SignSBOM

on:
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/signsbom.yml"
      - "cyclonedx-lib/**"

# Cancel existing runs if user makes another push.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test_sbom_sign:
    name: sign_sbom
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/centos7_build_image
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      # Build with jdk17 to ensure TemurinSignSBOM meets min compatibility
      - uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.10.0
        id: setup-java
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build TemurinSignSBOM.java
        run: |
          ant -noinput -buildfile cyclonedx-lib/build.xml clean
          ant -noinput -buildfile cyclonedx-lib/build.xml build-sign-sbom
          ant -noinput -buildfile cyclonedx-lib/build.xml build

      - name: Run TemurinSignSBOM Unit test
        run: |
          ant -noinput -buildfile cyclonedx-lib/build.xml runSignAndVerifySBOM

      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        name: Collect and Archive TemurinSignSBOM Artifacts
        with:
          name: testSBOM
          path: cyclonedx-lib/build/testSBOM.json
